"""Initial migration

Revision ID: 3b07d4708b40
Revises: 
Create Date: 2025-11-23 17:55:43.561556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b07d4708b40"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "autores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("nacionalidad", sa.String(length=50), nullable=False),
        sa.Column("bibliografia", sa.String(length=500), nullable=True),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_autores_id"), "autores", ["id"], unique=False)
    op.create_table(
        "categorias",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=500), nullable=True),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_index(op.f("ix_categorias_id"), "categorias", ["id"], unique=False)
    op.create_table(
        "editoriales",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_editoriales_id"), "editoriales", ["id"], unique=False)
    op.create_table(
        "tbl_usuarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("nombre_usuario", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("contraseña_hash", sa.String(length=255), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("es_admin", sa.Boolean(), nullable=True),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tbl_usuarios_email"), "tbl_usuarios", ["email"], unique=True
    )
    op.create_index(op.f("ix_tbl_usuarios_id"), "tbl_usuarios", ["id"], unique=False)
    op.create_index(
        op.f("ix_tbl_usuarios_nombre_usuario"),
        "tbl_usuarios",
        ["nombre_usuario"],
        unique=True,
    )
    op.create_table(
        "items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("tipo_item", sa.String(length=20), nullable=False),
        sa.Column("disponible", sa.Boolean(), nullable=True),
        sa.Column("id_autor", sa.UUID(), nullable=False),
        sa.Column("id_categoria", sa.UUID(), nullable=True),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_autor"],
            ["autores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_categoria"],
            ["categorias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=False)
    op.create_table(
        "libros",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("isbn", sa.String(length=20), nullable=True),
        sa.Column("numero_paginas", sa.String(length=10), nullable=True),
        sa.Column("id_editorial", sa.UUID(), nullable=False),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_editorial"],
            ["editoriales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isbn"),
    )
    op.create_index(op.f("ix_libros_id"), "libros", ["id"], unique=False)
    op.create_table(
        "periodicos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("fecha_publicacion", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id_editorial", sa.UUID(), nullable=False),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_editorial"],
            ["editoriales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_periodicos_id"), "periodicos", ["id"], unique=False)
    op.create_table(
        "revistas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("numero_publicacion", sa.String(length=50), nullable=True),
        sa.Column("id_editorial", sa.UUID(), nullable=False),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_editorial"],
            ["editoriales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revistas_id"), "revistas", ["id"], unique=False)
    op.create_table(
        "prestamos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_item", sa.UUID(), nullable=False),
        sa.Column("id_usuario", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_prestamo",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "fecha_devolucion_estimada", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("fecha_devolucion_real", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=True),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_item"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["tbl_usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prestamos_id"), "prestamos", ["id"], unique=False)
    op.create_table(
        "multas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_prestamo", sa.UUID(), nullable=False),
        sa.Column("id_usuario", sa.UUID(), nullable=False),
        sa.Column("monto", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("motivo", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_multa",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_pago", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=True),
        sa.Column("id_usuario_creacion", sa.UUID(), nullable=False),
        sa.Column("id_usuario_edicion", sa.UUID(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_actualizacion", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_prestamo"],
            ["prestamos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["tbl_usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id_prestamo"),
    )
    op.create_index(op.f("ix_multas_id"), "multas", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_multas_id"), table_name="multas")
    op.drop_table("multas")
    op.drop_index(op.f("ix_prestamos_id"), table_name="prestamos")
    op.drop_table("prestamos")
    op.drop_index(op.f("ix_revistas_id"), table_name="revistas")
    op.drop_table("revistas")
    op.drop_index(op.f("ix_periodicos_id"), table_name="periodicos")
    op.drop_table("periodicos")
    op.drop_index(op.f("ix_libros_id"), table_name="libros")
    op.drop_table("libros")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_tbl_usuarios_nombre_usuario"), table_name="tbl_usuarios")
    op.drop_index(op.f("ix_tbl_usuarios_id"), table_name="tbl_usuarios")
    op.drop_index(op.f("ix_tbl_usuarios_email"), table_name="tbl_usuarios")
    op.drop_table("tbl_usuarios")
    op.drop_index(op.f("ix_editoriales_id"), table_name="editoriales")
    op.drop_table("editoriales")
    op.drop_index(op.f("ix_categorias_id"), table_name="categorias")
    op.drop_table("categorias")
    op.drop_index(op.f("ix_autores_id"), table_name="autores")
    op.drop_table("autores")
    # ### end Alembic commands ###
